create table products
(
    product_id   bigint generated by default as identity,
    product_name varchar(255) unique,
    supplier_id  bigint,
    primary key (product_id)
);

create table suppliers
(
    supplier_id   bigint generated by default as identity,
    supplier_name varchar(255) unique,
    primary key (supplier_id)
);
alter table if exists products
    add constraint FK6i174ixi9087gcvvut45em7fd
        foreign key (supplier_id)
            references suppliers;

