CREATE TABLE suppliers (
                           supplier_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           supplier_name VARCHAR(255)
);
CREATE TABLE orders (
                        order_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        order_details VARCHAR(255),
                        creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        status VARCHAR(255),
                        supplier_id BIGINT,
                        FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

CREATE TABLE products (
                          product_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          product_name VARCHAR(255),
                          product_price DECIMAL(10, 2) NOT NULL
);



CREATE TABLE supplier_products (
                                   supplier_id BIGINT NOT NULL,
                                   product_id BIGINT NOT NULL,
                                   PRIMARY KEY (supplier_id, product_id),
                                   FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
                                   FOREIGN KEY (product_id) REFERENCES products(product_id)
);
CREATE TABLE order_items (
                             order_Item_Id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL,
                             FOREIGN KEY (order_id) REFERENCES orders (order_id),
                             FOREIGN KEY (product_id) REFERENCES products (product_id)
);