services:

  orders:
    depends_on:
      - orders_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    container_name: orders
    environment:
      - DATABASE_HOST=orders_db
  orders_db:
    image: postgres:latest
    container_name: orders_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234

