spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: none

  application:
    name: orders
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
logging:
  level:
    org.hibernate: info
