version: "1"

services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: application.properties
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c log_statement=all

networks:
  my-network:
    driver: bridge