server:
  port: 8082
spring:
  application:
    name: accounting

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5432}/accounting
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000

  flyway:
    locations: classpath:/db/migration
    schemas: public
    baselineOnMigrate: true
    enabled: true
    sqlMigrationPrefix: V
    sqlMigrationSuffixes: .sql
    cleanDisabled: false