create table product
(
    product_id   bigint generated by default as identity,
    product_name varchar(255) unique,
    product_price decimal(7,2),
    product_info varchar(255),
    product_quantity int,
    moved_at TIMESTAMP,
    movement_type VARCHAR(255),

    primary key (product_id)
);